### ISSUE TITLE
[FEAT] 서버 개발

### ISSUE THREAD

**Issue by devryyeong** [HDD-kiosk/HDD#21]
## 어떤 기능인가요?
음성인식 API용 서버 개발
TTS: kakao
STT: naver
참고: https://api.ncloud-docs.com/docs/ai-naver-clovaspeechrecognition 

## To Dos

- [ ] 서버-클라이언트 Firebase RESTful API 통신 구현
- [ ] (텍스트 안에서 메뉴 이름과 수량 구분하는 파싱 로직)

**Comment by devryyeong** [comment]
⬆마일스톤 제일 잘 활용하는사람 ㅋㅋㅋㅋ

**Comment by singsoong** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아무도 안했길래 했지...ㅎ
